### ISSUE TITLE
missing code

### ISSUE THREAD

**Issue by cnrad** [maxichrome/reminderer#1]
![image](https://user-images.githubusercontent.com/83192247/168404794-4db9643e-b45d-4eea-96eb-f87ddb81a5b7.png)

**Comment by maxichrome** [comment]
omg thank you for pointing this out, will work on this soon and close when a patch is pushed

**Comment by maxichrome** [comment]
fixed in ada1afb95dfe8ff52436313dfcdba9e3ecc4159e
